apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-home
  namespace: k3s-home
  labels:
    app: k3s-home
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k3s-home
  template:
    metadata:
      labels:
        app: k3s-home
    spec:
      containers:
      - name: k3s-home
        image: nginx
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: nginx-html
        configMap:
          name: nginx-html
