apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k3s-home

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: nginx-html
    files:
    - index.html
