# Deploys postgres in the production-services namespace
apiVersion: v1
kind: Namespace
metadata:
  name: production-services
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: production-services
  labels:
    app: postgres
type: Opaque
data:
  postgres-password: bXktcHJvZHVjdGlvbi1wYXNzd29yZAo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: production-services
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:12
          imagePullPolicy: Always
          ports:
            - name: tcp
              containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_DB
              value: todo
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: production-services
  labels:
    app: postgres
spec:
  selector:
    app: postgresql
  ports:
    - name: pgsql
      port: 5432
      targetPort: 5432
  type: LoadBalancer
