# This ConfigMap contains a ServiceAccount granting it RBACs via ClusterRole and ClusterRoleBinding
# Finally a Secret of type kubernetes.io/service-account-token is created to get token associated
# with the newly create ServiceAccount
apiVersion: v1
data:
  federation-rem-rbac-kdd.yaml: |
    kind: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: tigera-federation-remote-cluster
    rules:
    - apiGroups: [""]
      resources:
      - namespaces
      - serviceaccounts
      - services
      - endpoints
      - pods
      - nodes
      verbs:
      - get
      - list
      - watch
    - apiGroups: ["crd.projectcalico.org"]
      resources:
      - hostendpoints
      - ipamblocks
      - ippools
      verbs:
      - get
      - list
      - watch

    ---

    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: tigera-federation-remote-cluster
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: tigera-federation-remote-cluster
    subjects:
    - kind: ServiceAccount
      name: tigera-federation-remote-cluster
      namespace: kube-system
  federation-remote-sa.yaml: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: tigera-federation-remote-cluster
      namespace: kube-system

    ---

    apiVersion: v1
    kind: Secret
    type: kubernetes.io/service-account-token
    metadata:
      name: tigera-federation-remote-cluster
      namespace: kube-system
      annotations:
        kubernetes.io/service-account.name: "tigera-federation-remote-cluster"
kind: ConfigMap
metadata:
  name: federation-resources
  namespace: default
