apiVersion: config.projectsveltos.io/v1alpha1
kind: ClusterProfile
metadata:
  name: clusterprofile-nginx
spec:
  clusterSelector: tier: frontend 
  syncMode: Continuous
  helmCharts:
  - repositoryURL: https://helm.nginx.com/stable
    repositoryName: nginx-stable
    chartName: nginx-stable/nginx-ingress
    chartVersion: 0.17.1
    releaseName: nginx-latest
    releaseNamespace: nginx
    helmChartAction: Install
