apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: deploy-cleaner
spec:
  clusterSelector:
    matchLabels:
      env: fv
  policyRefs:
  - name: install-cleaner
    namespace: default
    kind: ConfigMap
  - name: pod-with-outdated-secret
    namespace: default
    kind: ConfigMap
  - name: unused-configmaps
    namespace: default
    kind: ConfigMap